# Generated by Django 4.0.4 on 2022-09-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categrie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categrie',
            new_name='Categorie',
        ),
    ]
