# Generated by Django 4.0.4 on 2022-09-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_habitat_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_Habitat', to='blog.categorie'),
        ),
    ]
