# Generated by Django 4.0.4 on 2022-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_habitat_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=500)),
                ('job', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('date_rdv', models.DateTimeField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
